apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80

#Commands
#kubectl get svc
#kubectl describe svc nginx-svc